Adjustment for self-hosted runner

diff --git a/.github/workflows/run-k8s-tests-on-zvsi.yaml b/.github/workflows/run-k8s-tests-on-zvsi.yaml
--- a/.github/workflows/run-k8s-tests-on-zvsi.yaml
+++ b/.github/workflows/run-k8s-tests-on-zvsi.yaml
@@ -23,61 +23,61 @@ on:
         default: ""
 
 jobs:
-  run-k8s-tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        vmm:
-          - qemu
-        snapshotter:
-          - devmapper
-        k8s:
-          - k3s
-    runs-on: s390x
-    env:
-      DOCKER_REGISTRY: ${{ inputs.registry }}
-      DOCKER_REPO: ${{ inputs.repo }}
-      DOCKER_TAG: ${{ inputs.tag }}
-      PR_NUMBER: ${{ inputs.pr-number }}
-      KATA_HYPERVISOR: ${{ matrix.vmm }}
-      KUBERNETES: "k3s"
-      SNAPSHOTTER: ${{ matrix.snapshotter }}
-      USING_NFD: "true"
-      TARGET_ARCH: "s390x"
-    steps:
-      - name: Take a pre-action for self-hosted runner
-        run: ${HOME}/script/pre_action.sh ubuntu-2204
-
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.commit-hash }}
-          fetch-depth: 0
-
-      - name: Rebase atop of the latest target branch
-        run: |
-          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
-        env:
-          TARGET_BRANCH: ${{ inputs.target-branch }}
-
-      - name: Deploy ${{ matrix.k8s }}
-        run: bash tests/integration/kubernetes/gha-run.sh deploy-k8s
-
-      - name: Configure the ${{ matrix.snapshotter }} snapshotter
-        run: bash tests/integration/kubernetes/gha-run.sh configure-snapshotter
-
-      - name: Deploy Kata
-        timeout-minutes: 10
-        run: bash tests/integration/kubernetes/gha-run.sh deploy-kata-zvsi
-
-      - name: Run tests
-        timeout-minutes: 30
-        run: bash tests/integration/kubernetes/gha-run.sh run-tests
-
-      - name: Take a post-action
-        if: always()
-        run: |
-          bash tests/integration/kubernetes/gha-run.sh cleanup-zvsi || true
-          ${HOME}/script/post_action.sh ubuntu-2204
+#  run-k8s-tests:
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        vmm:
+#          - qemu
+#        snapshotter:
+#          - devmapper
+#        k8s:
+#          - k3s
+#    runs-on: s390x
+#    env:
+#      DOCKER_REGISTRY: ${{ inputs.registry }}
+#      DOCKER_REPO: ${{ inputs.repo }}
+#      DOCKER_TAG: ${{ inputs.tag }}
+#      PR_NUMBER: ${{ inputs.pr-number }}
+#      KATA_HYPERVISOR: ${{ matrix.vmm }}
+#      KUBERNETES: "k3s"
+#      SNAPSHOTTER: ${{ matrix.snapshotter }}
+#      USING_NFD: "true"
+#      TARGET_ARCH: "s390x"
+#    steps:
+#      - name: Take a pre-action for self-hosted runner
+#        run: ${HOME}/script/pre_action.sh ubuntu-2204
+#
+#      - uses: actions/checkout@v4
+#        with:
+#          ref: ${{ inputs.commit-hash }}
+#          fetch-depth: 0
+#
+#      - name: Rebase atop of the latest target branch
+#        run: |
+#          ./tests/git-helper.sh "rebase-atop-of-the-latest-target-branch"
+#        env:
+#          TARGET_BRANCH: ${{ inputs.target-branch }}
+#
+#      - name: Deploy ${{ matrix.k8s }}
+#        run: bash tests/integration/kubernetes/gha-run.sh deploy-k8s
+#
+#      - name: Configure the ${{ matrix.snapshotter }} snapshotter
+#        run: bash tests/integration/kubernetes/gha-run.sh configure-snapshotter
+#
+#      - name: Deploy Kata
+#        timeout-minutes: 10
+#        run: bash tests/integration/kubernetes/gha-run.sh deploy-kata-zvsi
+#
+#      - name: Run tests
+#        timeout-minutes: 30
+#        run: bash tests/integration/kubernetes/gha-run.sh run-tests
+#
+#      - name: Take a post-action
+#        if: always()
+#        run: |
+#          bash tests/integration/kubernetes/gha-run.sh cleanup-zvsi || true
+#          ${HOME}/script/post_action.sh ubuntu-2204
 
   run-k8s-tests-coco-nontee:
     strategy:
@@ -89,7 +89,7 @@ jobs:
           - nydus
         pull-type:
           - guest-pull
-    runs-on: ubuntu-latest
+    runs-on: s390x-test
     env:
       DOCKER_REGISTRY: ${{ inputs.registry }}
       DOCKER_REPO: ${{ inputs.repo }}
